const commissionsData = [
    {
        id: "E1",
        tasks: [
            {
                name: "Add new maps",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Movement System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Spectate System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Check player req",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
        ],
    },
    {
        id: "E2",
        tasks: [
            {
                name: "Gamepass Shop",
                percentage: 100,
                status: 2,
                description: "",
                date: "",
            },
            {
                name: "Emotes Menu",
                percentage: 100,
                status: 2,
                description: "",
                date: "",
            },
            {
                name: "Tools Tab",
                percentage: 0,
                status: 1,
                description: "",
                date: "",
            },
            {
                name: "Ragdoll Command",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Remove Sword Fix",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
        ],
    },
    {
        id: "E3",
        tasks: [
            {
                name: "Economy System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Statistics Shower",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Shop System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Quest Giver NPC",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Robbing System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Doors System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
        ],
    },
];
