const commissionsData = [
    {
        id: "E1",
        tasks: [
            {
                name: "Add new maps",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Movement System",
                percentage: 100,
                status: 2,
                description: "",
                date: "",
            },
            {
                name: "Check player req",
                percentage: 100,
                status: 2,
                description: "",
                date: "",
            },
            {
                name: "Knife System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
        ],
    },
    {
        id: "E2",
        tasks: [
            {
                name: "Gamepass Shop",
                percentage: 100,
                status: 2,
                description: "",
                date: "",
            },
            {
                name: "Emotes Menu",
                percentage: 100,
                status: 2,
                description: "",
                date: "",
            },
            {
                name: "Tools Tab",
                percentage: 100,
                status: 2,
                description: "",
                date: "",
            },
            {
                name: "Ragdoll Command",
                percentage: 100,
                status: 2,
                description: "",
                date: "",
            },
            {
                name: "Remove Sword Fix",
                percentage: 100,
                status: 2,
                description: "",
                date: "",
            },
            {
                name: "WAITING FOR PAYMENT",
                percentage: 100,
                status: 4,
                description: "",
                date: "",
            },
        ],
    },
    {
        id: "E5",
        tasks: [
            {
                name: "Name-Tag System",
                percentage: 100,
                status: 2,
                description: "",
                date: "",
            },
            {
                name: "Level System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Shop System ",
                percentage: 30,
                status: 1,
                description: "Currently working on UIs",
                date: "",
            },
            {
                name: "Gamepasses",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Info UI",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Settings UI",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Music UI / Leaderstats / Whitelist Stuff",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Chat Colour / Tag Colour",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
        ],
    },
    {
        id: "L1",
        tasks: [
            {
                name: "Cooking System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Conveyor System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "NPC System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Table Claiming",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Tablet Ordering",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Fridge System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Shelf and Cutting",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Loading Screen",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Gamepasses",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Points System",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "Music System ",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
            {
                name: "UIS",
                percentage: 0,
                status: 0,
                description: "",
                date: "",
            },
        ],
    },
];
